package com.zjgt.paySys.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * CiticInvokeLog generated by hbm2java
 */
@Entity
@Table(name = "citic_invoke_log")
public class CiticInvokeLog implements java.io.Serializable {

	private String id;
	private String invokeUser;
	private String invokeCode;
	private String clientNo;
	private String invokeParameters;
	private String invokeResult;
	private Date createDate;
	private Short status;

	public CiticInvokeLog() {
	}

	public CiticInvokeLog(String id, Date createDate) {
		this.id = id;
		this.createDate = createDate;
	}

	public CiticInvokeLog(String id, String invokeUser, String invokeCode, String invokeParameters, String invokeResult,
			Date createDate, Short status) {
		this.id = id;
		this.invokeUser = invokeUser;
		this.invokeCode = invokeCode;
		this.invokeParameters = invokeParameters;
		this.invokeResult = invokeResult;
		this.createDate = createDate;
		this.status = status;
	}

	@Id
	@GenericGenerator(name = "idGenerator", strategy = "uuid")
	@GeneratedValue(generator = "idGenerator")
	@Column(name = "id", unique = true, nullable = false, length = 32)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "invoke_user", length = 100)
	public String getInvokeUser() {
		return this.invokeUser;
	}

	public void setInvokeUser(String invokeUser) {
		this.invokeUser = invokeUser;
	}

	@Column(name = "invoke_code", length = 50)
	public String getInvokeCode() {
		return this.invokeCode;
	}

	public void setInvokeCode(String invokeCode) {
		this.invokeCode = invokeCode;
	}

	@Column(name = "invoke_parameters", length = 65535)
	public String getInvokeParameters() {
		return this.invokeParameters;
	}

	public void setInvokeParameters(String invokeParameters) {
		this.invokeParameters = invokeParameters;
	}

	@Column(name = "invoke_result", length = 65535)
	public String getInvokeResult() {
		return this.invokeResult;
	}

	public void setInvokeResult(String invokeResult) {
		this.invokeResult = invokeResult;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_date", nullable = false, length = 19)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "status")
	public Short getStatus() {
		return this.status;
	}

	public void setStatus(Short status) {
		this.status = status;
	}
	
	@Column(name = "client_no", length = 20)
	public String getClientNo() {
		return clientNo;
	}

	public void setClientNo(String clientNo) {
		this.clientNo = clientNo;
	}

}
